/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CityCatalog;
import model.Patient;
import model.PatientDirectory;
import model.PersonDirectory;
import ui.Admin.AdminWorkAreaJPanel;
import ui.doctor.DoctorJPanel;
import ui.patient.PatientJPanel;

/**
 *
 * @author Dimple Patel
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private CityCatalog cityCatalog;
    private PatientDirectory patientDirectory;
    
    public LoginJPanel(JPanel userProcessContainer,PersonDirectory personDirectory, CityCatalog cityCatalog, PatientDirectory patientDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.cityCatalog = cityCatalog;
        this.patientDirectory = patientDirectory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        cmbLoginAs = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jplMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, 80));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password :");
        jplMain.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 140, -1));

        lblLoginAs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoginAs.setText("Login As :");
        jplMain.add(lblLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 140, -1));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("User ID :");
        jplMain.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 140, -1));

        cmbLoginAs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbLoginAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Patient", "Doctor" }));
        jplMain.add(cmbLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 250, 40));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jplMain.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 250, 40));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jplMain.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to Our Healthcare System...");
        jplMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 80));

        jpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jplMain.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\My Drive\\NEU MS\\AED\\Assignment\\Assignment4\\Dimpleben_Kanjibhai_Patel_AED_Assignment4\\HealthCareSystem\\src\\main\\java\\images\\healthcare-banner.jpg")); // NOI18N
        jplMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1954, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jplMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jplMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String loginAs = cmbLoginAs.getSelectedItem().toString();

        String username = txtUsername.getText();
        String password = new String(jpassword.getPassword());
        Long un;
        Patient patient = null;
        if(loginAs.equals("Admin")) {
            AdminWorkAreaJPanel awjp = new AdminWorkAreaJPanel(userProcessContainer,personDirectory, cityCatalog, patientDirectory);
            userProcessContainer.add("AdminWorkAreaJPanel", awjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(loginAs.equals("Patient")) {
            if(username.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Valid User Id", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                un = Long.parseLong(username);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please Enter Valid User Id", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            for(Patient p : patientDirectory.getPatientDirectory()) {
                if(p.getId().equals(un)) {
                    patient = p;
                    break;
                }
            }
            if(patient == null) {
                 JOptionPane.showMessageDialog(this, "User Id does not exists!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            PatientJPanel pjpl = new PatientJPanel(userProcessContainer,personDirectory, cityCatalog, patientDirectory, patient);
            userProcessContainer.add("PatientJPanel", pjpl);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);    
        }
        else if(loginAs.equals("Doctor")) {
            DoctorJPanel pjpl = new DoctorJPanel(userProcessContainer,personDirectory, cityCatalog, patientDirectory);
            userProcessContainer.add("DoctorJPanel", pjpl);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);    
        }
        else {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Username and Password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbLoginAs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JPanel jplMain;
    private javax.swing.JLabel lblLoginAs;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
