/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.doctor;

import ui.patient.*;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.CityCatalog;
import model.Community;
import model.Encounter;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;
import ui.Admin.PersonDirectoryJPanel;

/**
 *
 * @author Dimple Patel
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private CityCatalog cityCatalog;
    private PatientDirectory patientDirectory;
    private Person person;
    
    public DoctorJPanel(JPanel userProcessContainer,PersonDirectory personDirectory, CityCatalog cityCatalog, PatientDirectory patientDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.cityCatalog = cityCatalog;
        this.patientDirectory = patientDirectory;
        initComponents();
        setSize(1540,830);
       
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jblName3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerson1 = new javax.swing.JTable();
        jblName4 = new javax.swing.JLabel();
        jblName5 = new javax.swing.JLabel();
        jblName6 = new javax.swing.JLabel();
        txtBlood = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtTemperature = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Doctor Dashboard");

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jblName3.setBackground(new java.awt.Color(255, 255, 255));
        jblName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName3.setForeground(new java.awt.Color(0, 102, 102));
        jblName3.setText("Appointment Patient List :");

        tblPerson1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblPerson1.getTableHeader().setFont(new Font("Tahoma", 1, 18));
        tblPerson1.getTableHeader().setForeground(new java.awt.Color(0, 102, 102));
        tblPerson1.getTableHeader().setOpaque(false);
        tblPerson1.getTableHeader().setBackground(new java.awt.Color(255, 255, 255));
        tblPerson1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Id", "Patient Name", "Encounter Date", "Status", "Abnormal"
            }
        ));
        tblPerson1.setRowHeight(25);
        tblPerson1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(tblPerson1);

        jblName4.setBackground(new java.awt.Color(255, 255, 255));
        jblName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName4.setForeground(new java.awt.Color(0, 102, 102));
        jblName4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jblName4.setText("Blood Pressure :");

        jblName5.setBackground(new java.awt.Color(255, 255, 255));
        jblName5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName5.setForeground(new java.awt.Color(0, 102, 102));
        jblName5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jblName5.setText("Heart Rate :");

        jblName6.setBackground(new java.awt.Color(255, 255, 255));
        jblName6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName6.setForeground(new java.awt.Color(0, 102, 102));
        jblName6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jblName6.setText("Temperature :");

        txtBlood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBlood.setForeground(new java.awt.Color(0, 102, 102));

        txtHeartRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHeartRate.setForeground(new java.awt.Color(0, 102, 102));

        txtTemperature.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTemperature.setForeground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Vital Sign");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPerson1.getSelectedRow();

        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(tblPerson1.getValueAt(selectedRowIndex, 3).equals("Completed")){
            JOptionPane.showMessageDialog(null, "The task is already completed", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(txtBlood.getText().isEmpty() || txtHeartRate.getText().isEmpty()|| txtTemperature.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All Enter value for all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else {
            float bloodPressure;
            Integer heartRate;
            float temperature;
            try {
                bloodPressure = Float.parseFloat(txtBlood.getText());
                heartRate = Integer.parseInt(txtHeartRate.getText());
                temperature = Float.parseFloat(txtTemperature.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please Enter numeric value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Patient p = (Patient) tblPerson1.getValueAt(selectedRowIndex, 0);
            Encounter encounter = p.getEncounterHistory().addEncounter();
            encounter.setDate(p.getAppointmentDate());
            VitalSigns vitalSigns = encounter.createVitalSign();
            vitalSigns.setBloodPressure(bloodPressure);
            vitalSigns.setHeartRate(heartRate);
            vitalSigns.setTemperature(temperature);
            vitalSigns.isPatientAbnormal(p);
            p.setAppointmentDate(null);
            tblPerson1.setValueAt("Completed", selectedRowIndex, 3);
            tblPerson1.setValueAt(p.isIsNormal() ? "No" : "Yes", selectedRowIndex, 4);
            JOptionPane.showMessageDialog(this, "Successfully Added", "Info", JOptionPane.INFORMATION_MESSAGE);
            txtBlood.setText("");
            txtHeartRate.setText("");
            txtTemperature.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblName3;
    private javax.swing.JLabel jblName4;
    private javax.swing.JLabel jblName5;
    private javax.swing.JLabel jblName6;
    private javax.swing.JTable tblPerson1;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblPerson1.getModel();
        model.setRowCount(0);
        
        for (Person p : personDirectory.getPersonDirectory()) {
            if(p.getPatient().getAppointmentDate() != null) {
                Object row[] = new Object[5];
                row[0] = p.getPatient();
                row[1] = p.getFirstName() + " " + p.getLastName();
                row[2] = (p.getPatient().getAppointmentDate().getMonth() + 1) + "-" + (p.getPatient().getAppointmentDate().getDate()) + "-" + (p.getPatient().getAppointmentDate().getYear() + 1900);
                row[3] = "Pending";
                row[4] = p.getPatient().isIsNormal() ? "No" : "Yes";
                model.addRow(row);
            }

        }
        

}
}
