/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CityCatalog;
import model.Person;
import model.PersonDirectory;
import model.City;
import model.Community;
import model.House;
import model.PatientDirectory;

/**
 *
 * @author Dimple Patel
 */
public class AddPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPersonJPanel
     */
    private JPanel adminBodyJPanel;
    private PersonDirectory personDirectory;
    private PatientDirectory patientDirectory;
    private CityCatalog cityCatalog;
    
    public AddPersonJPanel(JPanel adminBodyJPanel, PersonDirectory personDirectory, CityCatalog cityCatalog, PatientDirectory patientDirectory) {
        this.adminBodyJPanel = adminBodyJPanel;
        this.personDirectory = personDirectory;
        this.cityCatalog = cityCatalog;
        this.patientDirectory = patientDirectory;
        initComponents();
        refreshCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblBirthdate = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        cmbCommunity = new javax.swing.JComboBox<>();
        lblHouseNO = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        btnAddPerson = new javax.swing.JButton();
        cmbHouseNo = new javax.swing.JComboBox<>();
        jdate = new com.toedter.calendar.JDateChooser();
        lblFirstName1 = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Add Person Details");

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName.setText(" First Name :");

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 102, 102));

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 102, 102));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastName.setText(" Last Name :");

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 102, 102));

        lblBirthdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(0, 102, 102));
        lblBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBirthdate.setText("Birthdate :");

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(0, 102, 102));
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhoneNumber.setText("Phone Number :");

        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(0, 102, 102));

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 102, 102));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCity.setText("City :");

        lblCommunity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCommunity.setForeground(new java.awt.Color(0, 102, 102));
        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCommunity.setText("Community :");

        cmbCommunity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCommunity.setForeground(new java.awt.Color(0, 102, 102));
        cmbCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCommunityActionPerformed(evt);
            }
        });

        lblHouseNO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHouseNO.setForeground(new java.awt.Color(0, 102, 102));
        lblHouseNO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHouseNO.setText("House No.  :");

        cmbCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCity.setForeground(new java.awt.Color(0, 102, 102));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        btnAddPerson.setBackground(new java.awt.Color(0, 102, 102));
        btnAddPerson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPerson.setText("Add Person");
        btnAddPerson.setBorderPainted(false);
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        cmbHouseNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbHouseNo.setForeground(new java.awt.Color(0, 102, 102));
        cmbHouseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHouseNoActionPerformed(evt);
            }
        });

        lblFirstName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFirstName1.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName1.setText(" SSN :");

        txtssn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtssn.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(btnAddPerson))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtPhoneNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHouseNO, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbCommunity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCity, cmbCommunity, txtFirstName, txtLastName, txtPhoneNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseNO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAddPerson)
                .addContainerGap(319, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminBodyJPanel.remove(this); 
        Component[] componentArray = adminBodyJPanel.getComponents();
        Component c = componentArray[componentArray.length - 1];
        PersonDirectoryJPanel ms = (PersonDirectoryJPanel) c;
        ms.refreshTable();
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.previous(adminBodyJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        
        if(txtFirstName.getText().isEmpty() || txtLastName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter First Name and Last Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Long phoneNo;
        //        number format check
        try {
            phoneNo = Long.parseLong(txtPhoneNumber.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check phone number formats", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        10 digit phone number validation check
        if (phoneNo.toString().length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone number should have 10 digit number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(jdate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Date of Birth", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txtssn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter SSN Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String regex = "^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$";
        String ssn = txtssn.getText();
        
         if (!ssn.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid SSN Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for(Person person : personDirectory.getPersonDirectory()) {
            if(person.getSsn().equals(ssn)) {
                JOptionPane.showMessageDialog(this, "SSN Number should be unique", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
         
        
        Person p = personDirectory.addPerson();
        p.setFirstName(txtFirstName.getText());
        p.setLastName(txtLastName.getText());
        p.setBirthDate(jdate.getDate());
        p.setPhoneNumber(phoneNo);
        p.setHouseId(cmbHouseNo.getSelectedItem().toString());
        p.setSsn(ssn);
        
        House h = (House)cmbHouseNo.getSelectedItem();
        h.addPerson(p);
        JOptionPane.showMessageDialog(null, "Person added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
        txtFirstName.setText("");
        txtLastName.setText("");
        txtPhoneNumber.setText("");
        txtssn.setText("");
        patientDirectory.addPatient(p.getPatient());
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
        City c = (City)cmbCity.getSelectedItem();
        cmbCommunity.removeAllItems();
        c.getCommunityList().forEach(community -> {
            cmbCommunity.addItem(community);
        });
        
        Community com = (Community)cmbCommunity.getSelectedItem();
        cmbHouseNo.removeAllItems();;
        com.getHouseList().forEach(house -> {
            cmbHouseNo.addItem(house);
        });
        
    }//GEN-LAST:event_cmbCityActionPerformed

    private void cmbHouseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHouseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHouseNoActionPerformed

    private void cmbCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCommunityActionPerformed
        // TODO add your handling code here:
        Community c = (Community)cmbCommunity.getSelectedItem();
        if(c != null) {
            cmbHouseNo.removeAllItems();;
            c.getHouseList().forEach(house -> {
                cmbHouseNo.addItem(house);
            });            
        }
    }//GEN-LAST:event_cmbCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<Object> cmbCity;
    private javax.swing.JComboBox<Object> cmbCommunity;
    private javax.swing.JComboBox<Object> cmbHouseNo;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblHouseNO;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtssn;
    // End of variables declaration//GEN-END:variables

    private void refreshCombo() {
        cmbCity.removeAllItems();
        cmbCommunity.removeAllItems();
        cmbHouseNo.removeAllItems();
        cityCatalog.getCityList().forEach(city -> {
            cmbCity.addItem(city);
        });
    }
}
