/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.CityCatalog;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Dimple Patel
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private CityCatalog cityCatalog;
    private PatientDirectory patientDirectory;
    
    public AdminWorkAreaJPanel(JPanel userProcessContainer,PersonDirectory personDirectory, CityCatalog cityCatalog, PatientDirectory patientDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.cityCatalog = cityCatalog;
        this.patientDirectory = patientDirectory;
        initComponents();
        
        PersonDirectoryJPanel pdjp = new PersonDirectoryJPanel(adminBodyJPanel, personDirectory, cityCatalog, patientDirectory);
        adminBodyJPanel.add("PersonDirectoryJPanel", pdjp);
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.next(adminBodyJPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPersonDir = new javax.swing.JButton();
        btnPatientDirectory1 = new javax.swing.JButton();
        btnAbnormalPatient = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        adminBodyJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Admin Work Area");

        btnPersonDir.setBackground(new java.awt.Color(255, 255, 255));
        btnPersonDir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPersonDir.setForeground(new java.awt.Color(0, 102, 102));
        btnPersonDir.setText("PersonDirectory");
        btnPersonDir.setBorderPainted(false);
        btnPersonDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonDirActionPerformed(evt);
            }
        });

        btnPatientDirectory1.setBackground(new java.awt.Color(255, 255, 255));
        btnPatientDirectory1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPatientDirectory1.setForeground(new java.awt.Color(0, 102, 102));
        btnPatientDirectory1.setText("PatientDirectory");
        btnPatientDirectory1.setBorderPainted(false);
        btnPatientDirectory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDirectory1ActionPerformed(evt);
            }
        });

        btnAbnormalPatient.setBackground(new java.awt.Color(255, 255, 255));
        btnAbnormalPatient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAbnormalPatient.setForeground(new java.awt.Color(0, 102, 102));
        btnAbnormalPatient.setText("Abnormal Patient Summary");
        btnAbnormalPatient.setBorderPainted(false);
        btnAbnormalPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalPatientActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 435, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnPersonDir, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPatientDirectory1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbnormalPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersonDir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatientDirectory1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbnormalPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jSplitPane2.setTopComponent(jPanel1);

        adminBodyJPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminBodyJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(adminBodyJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonDirActionPerformed
        // TODO add your handling code here:
        PersonDirectoryJPanel pdjp = new PersonDirectoryJPanel(adminBodyJPanel, personDirectory, cityCatalog, patientDirectory);
        adminBodyJPanel.add("PersonDirectoryJPanel", pdjp); 
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.next(adminBodyJPanel);
    }//GEN-LAST:event_btnPersonDirActionPerformed

    private void btnPatientDirectory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDirectory1ActionPerformed
        // TODO add your handling code here:
        PatientDirectoryJPanel pdjp = new PatientDirectoryJPanel(adminBodyJPanel, personDirectory, cityCatalog, patientDirectory);
        adminBodyJPanel.add("PatientDirectoryJPanel", pdjp);
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.next(adminBodyJPanel);
    }//GEN-LAST:event_btnPatientDirectory1ActionPerformed

    private void btnAbnormalPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalPatientActionPerformed
        // TODO add your handling code here:
        AbnormalPatientSummaryJPanel pdjp = new AbnormalPatientSummaryJPanel(adminBodyJPanel, personDirectory, cityCatalog, patientDirectory);
        adminBodyJPanel.add("AbnormalPatientSummaryJPanel", pdjp);
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.next(adminBodyJPanel); 
    }//GEN-LAST:event_btnAbnormalPatientActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminBodyJPanel;
    private javax.swing.JButton btnAbnormalPatient;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatientDirectory1;
    private javax.swing.JButton btnPersonDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
    }
