/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.City;
import model.CityCatalog;
import model.Community;
import model.House;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Dimple Patel
 */
public class UpdatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonJPanel
     */
    private JPanel adminBodyJPanel;
    private Person person;
    private CityCatalog cityCatalog;
    private PersonDirectory personDirectory;
    
    public UpdatePersonJPanel(JPanel adminBodyJPanel, Person person, CityCatalog cityCatalog,PersonDirectory personDirectory) {
        this.adminBodyJPanel = adminBodyJPanel;
        this.person = person;
        this.cityCatalog = cityCatalog;
        this.personDirectory = personDirectory;
        initComponents();
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtPhoneNumber.setText(person.getPhoneNumber().toString());
        txtssn.setText(person.getSsn());
        jdate.setDate(person.getBirthDate());
        refreshCombo();
        for(City city : cityCatalog.getCityList()) {
            for(Community community : city.getCommunityList()) {
                for(House house : community.getHouseList()) {
                    if(house.getHouseId().equals(person.getHouseId())) {
                        cmbCity.setSelectedItem(city);
                        cmbCommunity.setSelectedItem(community);
                        cmbHouseNo.setSelectedItem(house);
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbHouseNo = new javax.swing.JComboBox<>();
        btnAddPerson = new javax.swing.JButton();
        lblHouseNO = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        cmbCommunity = new javax.swing.JComboBox<>();
        lblCommunity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        lblFirstName1 = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbHouseNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbHouseNo.setForeground(new java.awt.Color(0, 102, 102));
        cmbHouseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHouseNoActionPerformed(evt);
            }
        });
        add(cmbHouseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 384, 203, 36));

        btnAddPerson.setBackground(new java.awt.Color(0, 102, 102));
        btnAddPerson.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPerson.setText("Update Person");
        btnAddPerson.setBorderPainted(false);
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });
        add(btnAddPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 449, -1, -1));

        lblHouseNO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHouseNO.setForeground(new java.awt.Color(0, 102, 102));
        lblHouseNO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHouseNO.setText("House No.  :");
        add(lblHouseNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 385, 174, 35));

        cmbCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCity.setForeground(new java.awt.Color(0, 102, 102));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });
        add(cmbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 286, 203, 36));

        cmbCommunity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCommunity.setForeground(new java.awt.Color(0, 102, 102));
        cmbCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCommunityActionPerformed(evt);
            }
        });
        add(cmbCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 335, 203, 36));

        lblCommunity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCommunity.setForeground(new java.awt.Color(0, 102, 102));
        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCommunity.setText("Community :");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 336, 174, 35));

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 102, 102));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCity.setText("City :");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 287, 174, 35));

        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 238, 202, 35));

        lblPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(0, 102, 102));
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhoneNumber.setText("Phone Number :");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 238, 174, 35));

        lblBirthdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(0, 102, 102));
        lblBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBirthdate.setText("Birthdate :");
        add(lblBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 137, 174, 35));

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 184, 202, 35));

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 102, 102));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastName.setText(" Last Name :");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 184, 174, 35));

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 137, 202, 35));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName.setText(" First Name :");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 137, 174, 35));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, 95, 34));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Update Person Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 26, 430, 55));
        add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 137, 226, 35));

        lblFirstName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFirstName1.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName1.setText(" SSN :");
        add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 185, 174, 35));

        txtssn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtssn.setForeground(new java.awt.Color(0, 102, 102));
        add(txtssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 184, 226, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminBodyJPanel.remove(this);
        Component[] componentArray = adminBodyJPanel.getComponents();
        Component c = componentArray[componentArray.length - 1];
        PersonDirectoryJPanel ms = (PersonDirectoryJPanel) c;
        ms.refreshTable();
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.previous(adminBodyJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCommunityActionPerformed
        // TODO add your handling code here:
        Community c = (Community)cmbCommunity.getSelectedItem();
        if(c != null) {
            cmbHouseNo.removeAllItems();;
            c.getHouseList().forEach(house -> {
                cmbHouseNo.addItem(house);
            });
        }
    }//GEN-LAST:event_cmbCommunityActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
        City c = (City)cmbCity.getSelectedItem();
        cmbCommunity.removeAllItems();
        c.getCommunityList().forEach(community -> {
            cmbCommunity.addItem(community);
        });

        Community com = (Community)cmbCommunity.getSelectedItem();
        cmbHouseNo.removeAllItems();;
        com.getHouseList().forEach(house -> {
            cmbHouseNo.addItem(house);
        });

    }//GEN-LAST:event_cmbCityActionPerformed

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        
        if(txtFirstName.getText().isEmpty() || txtLastName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter First Name and Last Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Long phoneNo;
        //        number format check
        try {
            phoneNo = Long.parseLong(txtPhoneNumber.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check phone number formats", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

//        10 digit phone number validation check
        if (phoneNo.toString().length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone number should have 10 digit number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(jdate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please Enter Date of Birth", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txtssn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter SSN Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String regex = "^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$";
        String ssn = txtssn.getText();
        
         if (!ssn.matches(regex)) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid SSN Number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for(Person p : personDirectory.getPersonDirectory()) {
            if(p.getSsn().equals(ssn) && !p.getId().equals(person.getId())) {
                JOptionPane.showMessageDialog(this, "SSN Number should be unique", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setBirthDate(jdate.getDate());
        person.setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
        cityCatalog.getCityList().forEach(city -> {
            city.getCommunityList().forEach(community -> {
                community.getHouseList().forEach(house -> {
                    if(house.getHouseId().equals(person.getHouseId())) {
                        house.removePerson(person);
                    }
                });
            });
        });
        person.setHouseId(cmbHouseNo.getSelectedItem().toString());

        House h = (House)cmbHouseNo.getSelectedItem();
        h.addPerson(person);
        JOptionPane.showMessageDialog(null, "Person Updated successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void cmbHouseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHouseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHouseNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<Object> cmbCity;
    private javax.swing.JComboBox<Object> cmbCommunity;
    private javax.swing.JComboBox<Object> cmbHouseNo;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblHouseNO;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtssn;
    // End of variables declaration//GEN-END:variables

    private void refreshCombo() {
        cmbCity.removeAllItems();
        cmbCommunity.removeAllItems();
        cmbHouseNo.removeAllItems();
        cityCatalog.getCityList().forEach(city -> {
            cmbCity.addItem(city);
        });
    }
}
