/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.CityCatalog;
import model.Community;
import model.House;
import model.Person;
import model.Patient;
import model.Encounter;
import model.PersonDirectory;

/**
 *
 * @author Dimple Patel
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePersonJPanel
     */
    private JPanel adminBodyJPanel;
    private Person person;
    private CityCatalog cityCatalog;
    private PersonDirectory personDirectory;
    
    public ViewPersonJPanel(JPanel adminBodyJPanel, Person person, CityCatalog cityCatalog,PersonDirectory personDirectory) {
        this.adminBodyJPanel = adminBodyJPanel;
        this.person = person;
        this.cityCatalog = cityCatalog;
        this.personDirectory = personDirectory;
        initComponents();
        
        ImageIcon imageIcon = new ImageIcon("G:\\My Drive\\NEU MS\\AED\\Assignment\\Assignment4\\Dimpleben_Kanjibhai_Patel_AED_Assignment4\\HealthCareSystem\\src\\main\\java\\images\\person.png"); 
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(150, 140,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back
        jblImageIcon.setIcon(imageIcon);
        jblImageIcon.setBounds(5, 5, 150, 120);
        
        
        jblNameText.setText(person.getFirstName() + " " + person.getLastName());
        jblBirthdate.setText((person.getBirthDate().getMonth() + 1) + "-" + (person.getBirthDate().getDate()+ 1) + "-" + (person.getBirthDate().getYear() + 1900));
        jblPhoneNo.setText(person.getPhoneNumber().toString());
        jblSSN.setText(person.getSsn());
        Patient p = person.getPatient();
        jblPatientId.setText(person.getPatient().getId().toString());
        City c = null;
        Community com = null;
        for(City city : cityCatalog.getCityList()) {
            for(Community community : city.getCommunityList()) {
                for(House house : community.getHouseList()) {
                    if(house.getHouseId().equals(person.getHouseId())) {
                         c = city;
                         com = community;
                    }
                }
            }
        }
        jblHouseId.setText(person.getHouseId() + ", " + com + ", " + c);
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jplPersonDetails = new javax.swing.JPanel();
        jblImageIcon = new javax.swing.JLabel();
        jblName = new javax.swing.JLabel();
        jblNameText = new javax.swing.JLabel();
        jblBirthdate = new javax.swing.JLabel();
        jblName1 = new javax.swing.JLabel();
        jblPhone = new javax.swing.JLabel();
        jblPhoneNo = new javax.swing.JLabel();
        jblPhone1 = new javax.swing.JLabel();
        jblPatientId = new javax.swing.JLabel();
        jblPhone2 = new javax.swing.JLabel();
        jblHouseId = new javax.swing.JLabel();
        jblPhone3 = new javax.swing.JLabel();
        jblSSN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        jblName2 = new javax.swing.JLabel();
        jblName3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerson1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText(" Person Details");

        jplPersonDetails.setBackground(new java.awt.Color(204, 204, 204));
        jplPersonDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 102, 102)));

        jblImageIcon.setIcon(new javax.swing.ImageIcon("G:\\My Drive\\NEU MS\\AED\\Assignment\\Assignment4\\Dimpleben_Kanjibhai_Patel_AED_Assignment4\\HealthCareSystem\\src\\main\\java\\images\\person.png")); // NOI18N

        jblName.setBackground(new java.awt.Color(255, 255, 255));
        jblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName.setForeground(new java.awt.Color(0, 102, 102));
        jblName.setText("Name :");

        jblNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblNameText.setForeground(new java.awt.Color(0, 102, 102));

        jblBirthdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblBirthdate.setForeground(new java.awt.Color(0, 102, 102));

        jblName1.setBackground(new java.awt.Color(255, 255, 255));
        jblName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName1.setForeground(new java.awt.Color(0, 102, 102));
        jblName1.setText("Birthdate :");

        jblPhone.setBackground(new java.awt.Color(255, 255, 255));
        jblPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblPhone.setForeground(new java.awt.Color(0, 102, 102));
        jblPhone.setText("Phone No. :");

        jblPhoneNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblPhoneNo.setForeground(new java.awt.Color(0, 102, 102));

        jblPhone1.setBackground(new java.awt.Color(255, 255, 255));
        jblPhone1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblPhone1.setForeground(new java.awt.Color(0, 102, 102));
        jblPhone1.setText("Patient Id :");

        jblPatientId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblPatientId.setForeground(new java.awt.Color(0, 102, 102));

        jblPhone2.setBackground(new java.awt.Color(255, 255, 255));
        jblPhone2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblPhone2.setForeground(new java.awt.Color(0, 102, 102));
        jblPhone2.setText("Address :");

        jblHouseId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblHouseId.setForeground(new java.awt.Color(0, 102, 102));

        jblPhone3.setBackground(new java.awt.Color(255, 255, 255));
        jblPhone3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblPhone3.setForeground(new java.awt.Color(0, 102, 102));
        jblPhone3.setText("SSN :");

        jblSSN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jblSSN.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jplPersonDetailsLayout = new javax.swing.GroupLayout(jplPersonDetails);
        jplPersonDetails.setLayout(jplPersonDetailsLayout);
        jplPersonDetailsLayout.setHorizontalGroup(
            jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                        .addComponent(jblImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                                    .addComponent(jblName)
                                    .addGap(27, 27, 27)
                                    .addComponent(jblNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                                    .addComponent(jblName1)
                                    .addGap(27, 27, 27)
                                    .addComponent(jblBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                                    .addComponent(jblPhone)
                                    .addGap(26, 26, 26)
                                    .addComponent(jblPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                                    .addComponent(jblPhone3)
                                    .addGap(26, 26, 26)
                                    .addComponent(jblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                                    .addComponent(jblPhone1)
                                    .addGap(26, 26, 26)
                                    .addComponent(jblPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                        .addComponent(jblPhone2)
                        .addGap(27, 27, 27)
                        .addComponent(jblHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jplPersonDetailsLayout.setVerticalGroup(
            jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplPersonDetailsLayout.createSequentialGroup()
                        .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblPhone1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jblSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblPhone3))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplPersonDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jblHouseId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblPhone2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblPerson.getTableHeader().setFont(new Font("Tahoma", 1, 18));
        tblPerson.getTableHeader().setForeground(new java.awt.Color(0, 102, 102));
        tblPerson.getTableHeader().setOpaque(false);
        tblPerson.getTableHeader().setBackground(new java.awt.Color(255, 255, 255));
        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Person Id", "Name"
            }
        ));
        tblPerson.setRowHeight(25);
        tblPerson.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(tblPerson);
        if (tblPerson.getColumnModel().getColumnCount() > 0) {
            tblPerson.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jblName2.setBackground(new java.awt.Color(255, 255, 255));
        jblName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName2.setForeground(new java.awt.Color(0, 102, 102));
        jblName2.setText("Lives With :");

        jblName3.setBackground(new java.awt.Color(255, 255, 255));
        jblName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jblName3.setForeground(new java.awt.Color(0, 102, 102));
        jblName3.setText("Encounter History :");

        tblPerson1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblPerson1.getTableHeader().setFont(new Font("Tahoma", 1, 18));
        tblPerson1.getTableHeader().setForeground(new java.awt.Color(0, 102, 102));
        tblPerson1.getTableHeader().setOpaque(false);
        tblPerson1.getTableHeader().setBackground(new java.awt.Color(255, 255, 255));
        tblPerson1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Encounter Date", "Blood Pressure", "Heart Rate", "Temparature", "Abnormal"
            }
        ));
        tblPerson1.setRowHeight(25);
        tblPerson1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(tblPerson1);
        if (tblPerson1.getColumnModel().getColumnCount() > 0) {
            tblPerson1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jplPersonDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jblName2)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblName3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jplPersonDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        adminBodyJPanel.remove(this);
        CardLayout layout = (CardLayout) adminBodyJPanel.getLayout();
        layout.previous(adminBodyJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblBirthdate;
    private javax.swing.JLabel jblHouseId;
    private javax.swing.JLabel jblImageIcon;
    private javax.swing.JLabel jblName;
    private javax.swing.JLabel jblName1;
    private javax.swing.JLabel jblName2;
    private javax.swing.JLabel jblName3;
    private javax.swing.JLabel jblNameText;
    private javax.swing.JLabel jblPatientId;
    private javax.swing.JLabel jblPhone;
    private javax.swing.JLabel jblPhone1;
    private javax.swing.JLabel jblPhone2;
    private javax.swing.JLabel jblPhone3;
    private javax.swing.JLabel jblPhoneNo;
    private javax.swing.JLabel jblSSN;
    private javax.swing.JPanel jplPersonDetails;
    private javax.swing.JTable tblPerson;
    private javax.swing.JTable tblPerson1;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
        
        DefaultTableModel model1 = (DefaultTableModel) tblPerson1.getModel();
        model1.setRowCount(0);
        
        House h = null;
                for(City city : cityCatalog.getCityList()) {
            for(Community community : city.getCommunityList()) {
                for(House house : community.getHouseList()) {
                    if(house.getHouseId().equals(person.getHouseId())) {
                         h = house;
                    }
                }
            }
        }
        for (Person p : h.getPersonList()) {
            if(!p.equals(person)) {
                Object row[] = new Object[2];
                row[0] = p;
                row[1] = p.getFirstName() + " " + p.getLastName();
                model.addRow(row);
            }
        }
        
        for(Encounter encounter : person.getPatient().getEncounterHistory().getEncounterList()) {
                Object row[] = new Object[5];
                row[0] = (encounter.getDate().getMonth() + 1) + "-" + (encounter.getDate().getDate()+ 1) + "-" + (encounter.getDate().getYear() + 1900);
                row[1] = encounter.getVitalSigns().getBloodPressure();
                row[2] = encounter.getVitalSigns().getHeartRate();
                row[3] = encounter.getVitalSigns().getTemperature();
                row[4] = encounter.getVitalSigns().isIsAbnormal() ? "Yes" : "No";
                model1.addRow(row);
        }
    }
}
