/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carmanagement;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author antiy
 */
public class MainFrame extends javax.swing.JFrame {

    CarCatalog carCatalog;
    byte photo[] = null;
    ArrayList<ServiceRecord> serviceRecordList;

    public MainFrame() {
        this.carCatalog = new CarCatalog();
        serviceRecordList = new ArrayList();
        initComponents();
    }

    /**
     * Creates new form MainFrame
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CarCatalogPanel = new javax.swing.JPanel();
        createbtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        addShowPanel = new javax.swing.JPanel();
        addPanel = new javax.swing.JPanel();
        brandLabel = new javax.swing.JLabel();
        mdellbl = new javax.swing.JLabel();
        brandtxt = new javax.swing.JTextField();
        modeltxt = new javax.swing.JTextField();
        Colorlbl = new javax.swing.JLabel();
        colortxt = new javax.swing.JTextField();
        yearlbl = new javax.swing.JLabel();
        yeartxt = new javax.swing.JTextField();
        engineNumberlbl = new javax.swing.JLabel();
        engineNumbertxt = new javax.swing.JTextField();
        numberOfSeatslbl = new javax.swing.JLabel();
        numberOfSeatstxt = new javax.swing.JTextField();
        licensePlatelbl = new javax.swing.JLabel();
        licensePlatetxt = new javax.swing.JTextField();
        warrantyYearlbl = new javax.swing.JLabel();
        warrantyYeartxt = new javax.swing.JTextField();
        onamelbl = new javax.swing.JLabel();
        onametxt = new javax.swing.JTextField();
        oteleNumberlbl = new javax.swing.JLabel();
        oteleNumbertxt = new javax.swing.JTextField();
        oemaillbl = new javax.swing.JLabel();
        oemailtxt = new javax.swing.JTextField();
        olicenselbl = new javax.swing.JLabel();
        olicensetxt = new javax.swing.JTextField();
        ossnlbl = new javax.swing.JLabel();
        ossntxt = new javax.swing.JTextField();
        oaddresslbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oaddresstxt = new javax.swing.JTextArea();
        addCarbtn = new javax.swing.JButton();
        phototxt = new javax.swing.JTextField();
        photobtn = new javax.swing.JButton();
        photolbl = new javax.swing.JLabel();
        servicerecordlbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        descriptionlbl = new javax.swing.JLabel();
        descriptiontxt = new javax.swing.JTextField();
        mileagelbl = new javax.swing.JLabel();
        mileagetxt = new javax.swing.JTextField();
        costlbl = new javax.swing.JLabel();
        costtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        showcarPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel1.setText("Car Management System");

        CarCatalogPanel.setBackground(new java.awt.Color(204, 204, 204));
        CarCatalogPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Car Catalog"));

        createbtn.setText("Add Car");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });

        displaybtn.setText("Display Car");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarCatalogPanelLayout = new javax.swing.GroupLayout(CarCatalogPanel);
        CarCatalogPanel.setLayout(CarCatalogPanelLayout);
        CarCatalogPanelLayout.setHorizontalGroup(
            CarCatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarCatalogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CarCatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displaybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        CarCatalogPanelLayout.setVerticalGroup(
            CarCatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarCatalogPanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(createbtn)
                .addGap(18, 18, 18)
                .addComponent(displaybtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addShowPanel.setBackground(new java.awt.Color(204, 204, 204));
        addShowPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new Car Details"));

        brandLabel.setText("Brand");

        mdellbl.setText("Model");

        brandtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandtxtActionPerformed(evt);
            }
        });

        modeltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeltxtActionPerformed(evt);
            }
        });

        Colorlbl.setText("Color");

        yearlbl.setText("Year");

        engineNumberlbl.setText("Engine Number");

        numberOfSeatslbl.setText("Number of Seats");

        licensePlatelbl.setText("License Plate");

        licensePlatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licensePlatetxtActionPerformed(evt);
            }
        });

        warrantyYearlbl.setText("Warranty Year");

        warrantyYeartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyYeartxtActionPerformed(evt);
            }
        });

        onamelbl.setText("Owner Name");

        oteleNumberlbl.setText("Owner Telephone Number");

        oemaillbl.setText("Owner Email Address");

        oemailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oemailtxtActionPerformed(evt);
            }
        });

        olicenselbl.setText("Owner Driver License");

        ossnlbl.setText("Owner Social Security Number");

        oaddresslbl.setText("Owner Address");

        oaddresstxt.setColumns(20);
        oaddresstxt.setRows(5);
        jScrollPane1.setViewportView(oaddresstxt);

        addCarbtn.setText("Add car");
        addCarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarbtnActionPerformed(evt);
            }
        });

        photobtn.setText("Upload Car Photo");
        photobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photobtnActionPerformed(evt);
            }
        });

        servicerecordlbl.setText("Add Service Record of Car");

        datelbl.setText("Date");

        descriptionlbl.setText("Description");

        mileagelbl.setText("Mileage");

        mileagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileagetxtActionPerformed(evt);
            }
        });

        costlbl.setText("Cost ($)");

        jButton1.setText("Add Service Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(brandtxt)
                            .addComponent(modeltxt)
                            .addComponent(colortxt)
                            .addComponent(yeartxt)
                            .addComponent(engineNumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Colorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mdellbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(engineNumbertxt)
                            .addComponent(numberOfSeatslbl, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(numberOfSeatstxt)
                            .addComponent(licensePlatelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(licensePlatetxt)
                            .addComponent(warrantyYearlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warrantyYeartxt)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(addCarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(onamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onametxt)
                            .addComponent(oteleNumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oteleNumbertxt)
                            .addComponent(oemaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oemailtxt)
                            .addComponent(olicenselbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(olicensetxt)
                            .addComponent(ossnlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ossntxt)
                            .addComponent(oaddresslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(phototxt)
                            .addComponent(photobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(servicerecordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(costtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(costlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mileagetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mileagelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(descriptiontxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descriptionlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                        .addComponent(datetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(datelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jButton1))))
                    .addComponent(photolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(brandLabel)
                                    .addComponent(onamelbl))
                                .addGap(10, 10, 10)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(onametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                                .addComponent(servicerecordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mdellbl)
                            .addComponent(oteleNumberlbl)
                            .addComponent(datelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oteleNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Colorlbl)
                            .addComponent(oemaillbl)
                            .addComponent(descriptionlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearlbl)
                            .addComponent(olicenselbl)
                            .addComponent(mileagelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(olicensetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mileagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engineNumberlbl)
                            .addComponent(ossnlbl)
                            .addComponent(costlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engineNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ossntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfSeatslbl)
                            .addComponent(oaddresslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(numberOfSeatstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licensePlatelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licensePlatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(warrantyYearlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(warrantyYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(photobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phototxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        showcarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Show car details"));

        javax.swing.GroupLayout showcarPanelLayout = new javax.swing.GroupLayout(showcarPanel);
        showcarPanel.setLayout(showcarPanelLayout);
        showcarPanelLayout.setHorizontalGroup(
            showcarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1414, Short.MAX_VALUE)
        );
        showcarPanelLayout.setVerticalGroup(
            showcarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout addShowPanelLayout = new javax.swing.GroupLayout(addShowPanel);
        addShowPanel.setLayout(addShowPanelLayout);
        addShowPanelLayout.setHorizontalGroup(
            addShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addShowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(addShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addShowPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showcarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        addShowPanelLayout.setVerticalGroup(
            addShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addShowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(addShowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addShowPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showcarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CarCatalogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(973, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarCatalogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addShowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeltxtActionPerformed

    private void brandtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandtxtActionPerformed

    private void licensePlatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licensePlatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licensePlatetxtActionPerformed

    private void warrantyYeartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyYeartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warrantyYeartxtActionPerformed

    private void oemailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oemailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oemailtxtActionPerformed

//    Method to Display Car Details
    private void showCarDetails() {
        addShowPanel.removeAll();
        addShowPanel.repaint();
        addShowPanel.revalidate();
        
        Integer row = 0;
        Integer column = 0;
        Integer count = 1;

        for (Car car : carCatalog.cars) {

            JLabel carNoLabel = new JLabel("Car" + count.toString() + ":");
            row = row + 50;
            carNoLabel.setBounds(50, row, 110, 30);
            carNoLabel.setFont(new Font("Verdana", Font.PLAIN, 20));
            showcarPanel.add(carNoLabel);

//          Displaying Serive Record            
            JLabel carServiceRecord = new JLabel("Car Service Record:");
            carServiceRecord.setFont(new Font("Verdana", Font.PLAIN, 15));
            carServiceRecord.setBounds(550, row + 5, 250, 30);
            showcarPanel.add(carServiceRecord);

            String header[] = {"Date", "Description", "Mileage", "Cost($)"};
            Object data[][] = new Object[10][4];

            int i = 0;
            for (ServiceRecord serviceRecord : car.getServiceRecordList().getServiceRecordList()) {
                int j = 0;
                data[i][j++] = serviceRecord.getDate();
                data[i][j++] = serviceRecord.getDescription();
                data[i][j++] = serviceRecord.getMileage();
                data[i++][j++] = serviceRecord.getCost();
            }

            JTable carTable = new JTable(data, header);
            //        carTable.setRowHeight(150);
            carTable.setFillsViewportHeight(true);

            JScrollPane scrollPane = new JScrollPane(carTable);
            scrollPane.setBounds(550, row + 30, 600, 300);
            scrollPane.setVisible(true);
            showcarPanel.add(scrollPane);

//          Displaying Brand
            row = row + 30;
            JLabel showBrandLabel = new JLabel("Brand");
            showBrandLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showBrandLabel);

            JTextField showBrandText = new JTextField();
            showBrandText.setText(car.getCarDetails().getBrand());
            showBrandText.setBounds(160, row, 110, 30);
            showcarPanel.add(showBrandText);

//          Displaying Owner Name
            JLabel showNameLabel = new JLabel("Owner Name");
            showNameLabel.setBounds(300, row, 110, 30);
            showcarPanel.add(showNameLabel);

            JTextField showNameText = new JTextField();
            showNameText.setText(car.getOwnerDetails().getName());
            showNameText.setBounds(410, row, 110, 30);
            showcarPanel.add(showNameText);

//          Displayng Model
            row = row + 30;
            JLabel showModelLabel = new JLabel("Model");
            showModelLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showModelLabel);

            JTextField showModelText = new JTextField();
            showModelText.setText(car.getCarDetails().getModel());
            showModelText.setBounds(160, row, 110, 30);
            showcarPanel.add(showModelText);

//          Displaying Owner Telephone Number
            JLabel showTeleLabel = new JLabel("Telephone Number");
            showTeleLabel.setBounds(300, row, 110, 30);
            showcarPanel.add(showTeleLabel);

            JTextField showTeleText = new JTextField();
            showTeleText.setText(car.getOwnerDetails().getTelephoneNumber().toString());
            showTeleText.setBounds(410, row, 110, 30);
            showcarPanel.add(showTeleText);

//          Displayng Car Color
            row = row + 30;
            JLabel showColorLabel = new JLabel("Car Color");
            showColorLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showColorLabel);

            JTextField showColorText = new JTextField();
            showColorText.setText(car.getCarDetails().getColor());
            showColorText.setBounds(160, row, 110, 30);
            showcarPanel.add(showColorText);

//          Displaying Owner Email Address
            JLabel showEmailLabel = new JLabel("Email");
            showEmailLabel.setBounds(300, row, 110, 30);
            showcarPanel.add(showEmailLabel);

            JTextField showEmailText = new JTextField();
            showEmailText.setText(car.getOwnerDetails().getEmail());
            showEmailText.setBounds(410, row, 110, 30);
            showcarPanel.add(showEmailText);

//          Displayng Car Manufacturing Year
            row = row + 30;
            JLabel showYearLabel = new JLabel("Manufacturing Year");
            showYearLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showYearLabel);

            JTextField showYearText = new JTextField();
            showYearText.setText(car.getCarDetails().getYear().toString());
            showYearText.setBounds(160, row, 110, 30);
            showcarPanel.add(showYearText);

//          Displaying Owner Driver License
            JLabel showDriverLabel = new JLabel("Driver License");
            showDriverLabel.setBounds(300, row, 110, 30);
            showcarPanel.add(showDriverLabel);

            JTextField showDriverText = new JTextField();
            showDriverText.setText(car.getOwnerDetails().getDriverLicence());
            showDriverText.setBounds(410, row, 110, 30);
            showcarPanel.add(showDriverText);

//          Displayng Car Engine No.
            row = row + 30;
            JLabel showEngineLabel = new JLabel("Engine No.");
            showEngineLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showEngineLabel);

            JTextField showEngineText = new JTextField();
            showEngineText.setText(car.getCarDetails().getEngineNumber().toString());
            showEngineText.setBounds(160, row, 110, 30);
            showcarPanel.add(showEngineText);

//          Displaying Owner Social Security Number
            JLabel showSSNLabel = new JLabel("SSN");
            showSSNLabel.setBounds(300, row, 110, 30);
            showcarPanel.add(showSSNLabel);

            JTextField showSSNText = new JTextField();
            showSSNText.setText(car.getOwnerDetails().getSocialSecurityNumber());
            showSSNText.setBounds(410, row, 110, 30);
            showcarPanel.add(showSSNText);

//          Displayng Number of Seats
            row = row + 30;
            JLabel showSeatsLabel = new JLabel("No of Seats");
            showSeatsLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showSeatsLabel);

            JTextField showSeatsText = new JTextField();
            showSeatsText.setText(car.getCarDetails().getEngineNumber().toString());
            showSeatsText.setBounds(160, row, 110, 30);
            showcarPanel.add(showSeatsText);

//          Displaying Owner Address
            JLabel showAddressLabel = new JLabel("Address");
            showAddressLabel.setBounds(300, row, 110, 30);
            showcarPanel.add(showAddressLabel);

            JTextField showAddressText = new JTextField();
            showAddressText.setText(car.getOwnerDetails().getAddress());
            showAddressText.setBounds(410, row, 110, 30);
            showcarPanel.add(showAddressText);

//          Displayng License Plates
            row = row + 30;
            JLabel showPlateLabel = new JLabel("License Plates");
            showPlateLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showPlateLabel);

            JTextField showPlateText = new JTextField();
            showPlateText.setText(car.getCarDetails().getLicencePlate());
            showPlateText.setBounds(160, row, 110, 30);
            showcarPanel.add(showPlateText);

//          Displayng Warranty Year
            row = row + 30;
            JLabel showWarrantyLabel = new JLabel("Warranty Year");
            showWarrantyLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showWarrantyLabel);

            JTextField showWarrantyText = new JTextField();
            showWarrantyText.setText(car.getCarDetails().getWarrantyYear().toString());
            showWarrantyText.setBounds(160, row, 110, 30);
            showcarPanel.add(showWarrantyText);

//          Converting byte stream to image
            ByteArrayInputStream bis = new ByteArrayInputStream(car.getCarDetails().getPhoto());
            BufferedImage bImage = null;
            String imageName = "src/carmanagement/Created Images/output" + count + ".jpg";
            try {
                bImage = ImageIO.read(bis);
                ImageIO.write(bImage, "jpg", new File(imageName));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            row = row + 30;
            JLabel showImageLabel = new JLabel("Car Image");
            showImageLabel.setBounds(50, row, 110, 30);
            showcarPanel.add(showImageLabel);

            row = row + 30;
            JLabel showImageIconLabel = new JLabel("");
            showImageIconLabel.setBounds(50, row, 200, 200);
            String imageLocation = "src/carmanagement/Created Images/output" + count + ".jpg";
            showImageIconLabel.setIcon(new ImageIcon(new ImageIcon(imageLocation.toString()).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
            showcarPanel.add(showImageIconLabel);
            row = row + 200;
            count++;
        }

        showcarPanel.setPreferredSize(new Dimension(2000,2000));

        JScrollPane scrollPane = new JScrollPane(showcarPanel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setBounds(10, 10, 1300, 750);
        scrollPane.setVisible(true);


        addShowPanel.add(scrollPane);
        addShowPanel.repaint();
        addShowPanel.revalidate();
    }

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        addShowPanel.removeAll();
        addShowPanel.repaint();
        addShowPanel.revalidate();
        addShowPanel.add(addPanel);
        addShowPanel.repaint();
        addShowPanel.revalidate();
    }//GEN-LAST:event_createbtnActionPerformed

    private void addCarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarbtnActionPerformed
        // TODO add your handling code here:
//        Validate none of fields are null

        if (brandtxt.getText().isEmpty() || modeltxt.getText().isEmpty() || yeartxt.getText().isEmpty() || colortxt.getText().isEmpty() || engineNumbertxt.getText().isEmpty() || numberOfSeatstxt.getText().isEmpty()
                || licensePlatetxt.getText().isEmpty() || warrantyYeartxt.getText().isEmpty() || onametxt.getText().isEmpty() || oteleNumbertxt.getText().isEmpty()
                || oemailtxt.getText().isEmpty() || olicensetxt.getText().isEmpty() || ossntxt.getText().isEmpty() || oaddresstxt.getText().isEmpty() || phototxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter all fields", "Try again", JOptionPane.ERROR_MESSAGE);
        } else {

            String emailval = oemailtxt.getText();
            int ida = emailval.indexOf("@");
            int idd = emailval.indexOf(".", ida);
            String spt = "[0-9]+";
            Pattern pt = Pattern.compile(spt);
            Matcher myear = pt.matcher(yeartxt.getText());
            Matcher mengineNumber = pt.matcher(engineNumbertxt.getText());
            Matcher mnumberOfSeats = pt.matcher(numberOfSeatstxt.getText());
            Matcher mwarrantyYear = pt.matcher(warrantyYeartxt.getText());
            Matcher mtelephoneNumber = pt.matcher(oteleNumbertxt.getText());
            if (ida > idd && (idd - ida) < 1) {
                JOptionPane.showMessageDialog(this, "Please Enter valid email address", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (!myear.matches()) {
                JOptionPane.showMessageDialog(this, "Please Enter Numeric value for year", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (yeartxt.getText().toString().length() != 4) {
                JOptionPane.showMessageDialog(this, "Please Enter valid year like 1996", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (!mengineNumber.matches()) {
                JOptionPane.showMessageDialog(this, "Please Enter Numeric value for Engine Number", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (!mnumberOfSeats.matches()) {
                JOptionPane.showMessageDialog(this, "Please Enter Numeric value for Number of Seats", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (!mwarrantyYear.matches()) {
                JOptionPane.showMessageDialog(this, "Please Enter Numeric value for Warranty Year", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (warrantyYeartxt.getText().toString().length() != 4) {
                JOptionPane.showMessageDialog(this, "Please Enter valid value for Warranty Year", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (!mtelephoneNumber.matches()) {
                JOptionPane.showMessageDialog(this, "Please Enter Numeric value for telephone number", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (oteleNumbertxt.getText().toString().length() != 10) {
                JOptionPane.showMessageDialog(this, "Please Enter valid 10 digit telephone number", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.valueOf(numberOfSeatstxt.getText()) > 7) {
                JOptionPane.showMessageDialog(this, "Number of seats can not be more than 7", "Try again", JOptionPane.ERROR_MESSAGE);
            }
            else {
                int counter = 0;
                if (counter == 0) {
                    System.out.println("inside " + counter);

                    for (Car car : carCatalog.cars) {
                        if (car.getCarDetails().getLicencePlate().equals(licensePlatetxt.getText().toString()) ) {
                            counter++;
                            JOptionPane.showMessageDialog(this, "License Plate for car should be unique", "Try again", JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                    }
                }
                if (counter == 0) {
                    String brand = brandtxt.getText();
                    String model = modeltxt.getText();
                    Integer year = Integer.valueOf(yeartxt.getText());
                    String color = colortxt.getText();
                    Integer engineNumber = Integer.valueOf(engineNumbertxt.getText());
                    Integer numberOfSeats = Integer.valueOf(numberOfSeatstxt.getText());
                    String licencePlate = licensePlatetxt.getText();
                    Integer warrantyYear = Integer.valueOf(warrantyYeartxt.getText());
                    String name = onametxt.getText();
                    Long telephoneNumber = Long.valueOf(oteleNumbertxt.getText());
                    String email = oemailtxt.getText();
                    String driverLicence = olicensetxt.getText();
                    String socialSecurityNumber = ossntxt.getText();
                    String address = oaddresstxt.getText();

                    ArrayList<ServiceRecord> servicelist = new ArrayList();
                    for (ServiceRecord record : serviceRecordList) {
                        ServiceRecord rc = new ServiceRecord(record.getDate(), record.getDescription(), record.getMileage(), record.getCost());
                        servicelist.add(rc);
                    }

//            DefaultTableModel mdl = (DefaultTableModel) showCartable.getModel();
//            mdl.addRow(new Object[] { brand, model, color, year, engineNumber, numberOfSeats, licencePlate, warrantyYear,  name, telephoneNumber, email, driverLicence, socialSecurityNumber, address});
                    carCatalog.createNewCar(brand, model, color, year, engineNumber, numberOfSeats, licencePlate, warrantyYear, photo, name, telephoneNumber, email, driverLicence, socialSecurityNumber, address, servicelist);
                    serviceRecordList.clear();

                    this.showCarDetails();
                    brandtxt.setText("");
                    modeltxt.setText("");
                    yeartxt.setText("");
                    colortxt.setText("");
                    engineNumbertxt.setText("");
                    numberOfSeatstxt.setText("");
                    licensePlatetxt.setText("");
                    warrantyYeartxt.setText("");
                    onametxt.setText("");
                    oteleNumbertxt.setText("");
                    oemailtxt.setText("");
                    olicensetxt.setText("");
                    ossntxt.setText("");
                    oaddresstxt.setText("");
                    phototxt.setText("");
                    photolbl.setIcon(null);
                }
            }
        }
    }//GEN-LAST:event_addCarbtnActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        // TODO add your handling code here:
//        Calling showCar method
        this.showCarDetails();
    }//GEN-LAST:event_displaybtnActionPerformed

    private void photobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photobtnActionPerformed
        // TODO add your handling code here:
//        Select an image and convert it into byte stream
        String filename = null;
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(f.toString()).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        photolbl.setIcon(imageIcon);

        filename = f.getAbsolutePath();
        phototxt.setText(filename);
        phototxt.setColumns(4);

        try {
            File img = new File(filename);
            FileInputStream fis = new FileInputStream(img);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte buf[] = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                baos.write(buf, 0, readNum);
            }
            photo = baos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_photobtnActionPerformed

    private void mileagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileagetxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String date = datetxt.getText();
        String description = descriptiontxt.getText();
        String mileage = mileagetxt.getText();
        String cost = costtxt.getText();

        if (brandtxt.getText().isEmpty() || modeltxt.getText().isEmpty() || yeartxt.getText().isEmpty() || colortxt.getText().isEmpty() || engineNumbertxt.getText().isEmpty() || numberOfSeatstxt.getText().isEmpty()
                || licensePlatetxt.getText().isEmpty() || warrantyYeartxt.getText().isEmpty() || onametxt.getText().isEmpty() || oteleNumbertxt.getText().isEmpty()
                || oemailtxt.getText().isEmpty() || olicensetxt.getText().isEmpty() || ossntxt.getText().isEmpty() || oaddresstxt.getText().isEmpty() || phototxt.getText().isEmpty()
                || datetxt.getText().isEmpty() || descriptiontxt.getText().isEmpty() || mileagetxt.getText().isEmpty() || costtxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter all  fields", "Try again", JOptionPane.ERROR_MESSAGE);

        }

        serviceRecordList.add(new ServiceRecord(date, description, mileage, cost));

        datetxt.setText("");
        descriptiontxt.setText("");
        mileagetxt.setText("");
        costtxt.setText("");
        JOptionPane.showMessageDialog(this, "Add Successfully, Fill information again if you want to add more information", "Ok", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarCatalogPanel;
    private javax.swing.JLabel Colorlbl;
    private javax.swing.JButton addCarbtn;
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel addShowPanel;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField brandtxt;
    private javax.swing.JTextField colortxt;
    private javax.swing.JLabel costlbl;
    private javax.swing.JTextField costtxt;
    private javax.swing.JButton createbtn;
    private javax.swing.JLabel datelbl;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel descriptionlbl;
    private javax.swing.JTextField descriptiontxt;
    private javax.swing.JButton displaybtn;
    private javax.swing.JLabel engineNumberlbl;
    private javax.swing.JTextField engineNumbertxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel licensePlatelbl;
    private javax.swing.JTextField licensePlatetxt;
    private javax.swing.JLabel mdellbl;
    private javax.swing.JLabel mileagelbl;
    private javax.swing.JTextField mileagetxt;
    private javax.swing.JTextField modeltxt;
    private javax.swing.JLabel numberOfSeatslbl;
    private javax.swing.JTextField numberOfSeatstxt;
    private javax.swing.JLabel oaddresslbl;
    private javax.swing.JTextArea oaddresstxt;
    private javax.swing.JLabel oemaillbl;
    private javax.swing.JTextField oemailtxt;
    private javax.swing.JLabel olicenselbl;
    private javax.swing.JTextField olicensetxt;
    private javax.swing.JLabel onamelbl;
    private javax.swing.JTextField onametxt;
    private javax.swing.JLabel ossnlbl;
    private javax.swing.JTextField ossntxt;
    private javax.swing.JLabel oteleNumberlbl;
    private javax.swing.JTextField oteleNumbertxt;
    private javax.swing.JButton photobtn;
    private javax.swing.JLabel photolbl;
    private javax.swing.JTextField phototxt;
    private javax.swing.JLabel servicerecordlbl;
    private javax.swing.JPanel showcarPanel;
    private javax.swing.JLabel warrantyYearlbl;
    private javax.swing.JTextField warrantyYeartxt;
    private javax.swing.JLabel yearlbl;
    private javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
